// <auto-generated />
using System;
using API.Quotes.Limit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Quotes.Limit.Migrations
{
    [DbContext(typeof(QuotesDbContext))]
    [Migration("20250910190848_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Quotes.Limit.Models.StockQuote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("MarketCap")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("StockQuotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Apple Inc.",
                            MarketCap = 2500000000000L,
                            Price = 150.25m,
                            Symbol = "AAPL",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Microsoft Corporation",
                            MarketCap = 2200000000000L,
                            Price = 280.50m,
                            Symbol = "MSFT",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Alphabet Inc.",
                            MarketCap = 1800000000000L,
                            Price = 2700.75m,
                            Symbol = "GOOGL",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Amazon.com, Inc.",
                            MarketCap = 1700000000000L,
                            Price = 3300.10m,
                            Symbol = "AMZN",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "Tesla, Inc.",
                            MarketCap = 800000000000L,
                            Price = 700.30m,
                            Symbol = "TSLA",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "NVIDIA Corporation",
                            MarketCap = 900000000000L,
                            Price = 400.75m,
                            Symbol = "NVDA",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CompanyName = "Meta Platforms, Inc.",
                            MarketCap = 950000000000L,
                            Price = 350.60m,
                            Symbol = "FB",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CompanyName = "Netflix, Inc.",
                            MarketCap = 250000000000L,
                            Price = 500.20m,
                            Symbol = "NFLX",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CompanyName = "Alibaba Group Holding Limited",
                            MarketCap = 500000000000L,
                            Price = 200.15m,
                            Symbol = "BABA",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CompanyName = "Visa Inc.",
                            MarketCap = 480000000000L,
                            Price = 220.40m,
                            Symbol = "V",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
