// <auto-generated />
using System;
using API.Quotes.Limit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Quotes.Limit.Migrations
{
    [DbContext(typeof(QuotesContext))]
    [Migration("20250912172222_CreateData")]
    partial class CreateData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Quotes.Limit.Models.StockQuote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("MarketCap")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("StockQuotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Apple Inc",
                            MarketCap = 250000000000L,
                            Price = 150.25m,
                            Symbol = "AAPL",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Microsoft corporation",
                            MarketCap = 220000000000L,
                            Price = 150.25m,
                            Symbol = "MSFT",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Alphabet Inc",
                            MarketCap = 180000000000L,
                            Price = 150.25m,
                            Symbol = "GOOGL",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Tesla Inc",
                            MarketCap = 170000000000L,
                            Price = 150.25m,
                            Symbol = "TSLA",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "Amazon.com Inc",
                            MarketCap = 160000000000L,
                            Price = 145.80m,
                            Symbol = "AMZN",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "Meta Platforms Inc",
                            MarketCap = 90000000000L,
                            Price = 310.45m,
                            Symbol = "META",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CompanyName = "Netflix Inc",
                            MarketCap = 80000000000L,
                            Price = 420.75m,
                            Symbol = "NFLX",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CompanyName = "NVIDIA Corporation",
                            MarketCap = 150000000000L,
                            Price = 480.20m,
                            Symbol = "NVDA",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CompanyName = "Advanced Micro Devices Inc",
                            MarketCap = 70000000000L,
                            Price = 110.60m,
                            Symbol = "AMD",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CompanyName = "Intel Corporation",
                            MarketCap = 60000000000L,
                            Price = 35.90m,
                            Symbol = "INTC",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CompanyName = "Oracle Corporation",
                            MarketCap = 75000000000L,
                            Price = 88.15m,
                            Symbol = "ORCL",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CompanyName = "SAP SE",
                            MarketCap = 65000000000L,
                            Price = 135.45m,
                            Symbol = "SAP",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CompanyName = "Uber Technologies Inc",
                            MarketCap = 55000000000L,
                            Price = 42.75m,
                            Symbol = "UBER",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CompanyName = "Lyft Inc",
                            MarketCap = 10000000000L,
                            Price = 11.20m,
                            Symbol = "LYFT",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
